CREATE DATABASE QuanLyDiemSinhVien;
GO

USE QuanLyDiemSinhVien;
GO

CREATE TABLE USERS (
	id int IDENTITY NOT NULL,
	username NVARCHAR (30) NOT NULL UNIQUE,
	password NVARCHAR(250) NOT NULL,
	isAdmin INT NOT NULL
);
GO

CREATE TABLE SINHVIEN(
	id int IDENTITY NOT NULL,
	MASV CHAR (12) NOT NULL,
	HO NVARCHAR (250) NOT NULL,
	TEN NVARCHAR (250) NOT NULL,
	GIOITINH NVARCHAR (3) NULL,
	NGAYSINH DATE ,
	DANTOC NVARCHAR (250) NULL,
	DIACHI NVARCHAR (250) NULL,
	QUEQUAN NVARCHAR (30) NULL,
	SODIENTHOAI NVARCHAR(15) NULL,
	EMAIL NVARCHAR (250) NULL,
	KHOAHOC INT NOT NULL,
	MANGANH CHAR(6)

	PRIMARY KEY(id,MASV)
);
GO
CREATE TABLE NGANH (
	MANGANH CHAR (6) NOT NULL,
	TENNGANH NVARCHAR (250) NOT NULL,
	PRIMARY KEY (MANGANH)
);
GO

CREATE TABLE LOPHOCPHAN (
	id int IDENTITY NOT NULL,
	MAMH CHAR(12) NOT NULL,
	MALOP CHAR(12) NOT NULL,
	TENGIANGVIEN NVARCHAR(250) NOT NULL,
	PHONGHOC NVARCHAR (250),
	NGAYBATDAU  DATETIME,
	NGAYKETTHUC  DATETIME,
	SOLUONGSINHVIEN INT,
	PRIMARY KEY (MALOP)
);
GO
CREATE PROC sp_addLopHocPhan(
	@MAMH CHAR(12) ,
	@MALOP CHAR(12) ,
	@TENGIANGVIEN NVARCHAR(250),
	@PHONGHOC NVARCHAR (250),
	@NGAYBATDAU  DATETIME,
	@NGAYKETTHUC  DATETIME,
	@SOLUONGSINHVIEN INT
)
AS
INSERT INTO LOPHOCPHAN(MAMH,MALOP,TENGIANGVIEN,PHONGHOC,NGAYBATDAU,NGAYKETTHUC,SOLUONGSINHVIEN)
VALUES (@MAMH,@MALOP,@TENGIANGVIEN,@PHONGHOC,@NGAYBATDAU,@NGAYKETTHUC,@SOLUONGSINHVIEN)
GO

CREATE PROC sp_editLopHocPhan(
	@MALOP CHAR(12) ,
	@TENGIANGVIEN NVARCHAR(250),
	@PHONGHOC NVARCHAR (250),
	@NGAYBATDAU  DATETIME,
	@NGAYKETTHUC  DATETIME,
	@SOLUONGSINHVIEN INT
)
AS
UPDATE LOPHOCPHAN
SET TENGIANGVIEN = @TENGIANGVIEN, PHONGHOC = @PHONGHOC,NGAYBATDAU = @NGAYBATDAU,NGAYKETTHUC = @NGAYKETTHUC,SOLUONGSINHVIEN = @SOLUONGSINHVIEN
WHERE MALOP = @MALOP
GO

CREATE PROC sp_getAllLop
AS
SELECT * FROM LOPHOCPHAN
ORDER BY LOPHOCPHAN.id DESC
GO

CREATE PROC sp_searchLopHocPhan(
	@TEN NVARCHAR (250) 
)
AS
select * from LOPHOCPHAN
WHERE LOPHOCPHAN.MAMH LIKE '%' + @TEN + '%' OR LOPHOCPHAN.MALOP LIKE '%' + @TEN + '%' OR LOPHOCPHAN.TENGIANGVIEN LIKE '%' + @TEN + '%'
GO

CREATE PROC sp_deleteLopHocPhan(
 	@MALOP CHAR(12) 
)
AS
DELETE FROM LOPHOCPHAN WHERE LOPHOCPHAN.MALOP = @MALOP
CREATE TABLE USERS_SINHVIEN(
	user_id  int NOT NULL,
	MASV CHAR (6) NOT NULL,

);
GO

CREATE PROC sp_login(
	@username NVARCHAR (30)  ,
	@password NVARCHAR(250) 
)
AS
SELECT * FROM USERS WHERE USERS.username = @username AND USERS.password = @password;
GO

CREATE PROC sp_createUser(
	@username NVARCHAR (30),
	@password NVARCHAR(250),
	@isAdmin INT 
)
AS
INSERT INTO USERS(username,password,isAdmin)
VALUES (@username,@password,@isAdmin)
GO

CREATE PROC sp_deleteUser(
	@username NVARCHAR(30)
)
AS
DELETE FROM USERS WHERE USERS.username = @username
GO

CREATE PROC sp_changepassword(
	@username NVARCHAR (30),
	@password NVARCHAR(250)
)
AS
UPDATE USERS
SET USERS.password = @password
WHERE USERS.username = @username
GO

CREATE PROC sp_addSinhVien(
	@MASV CHAR (12) ,
	@HO NVARCHAR (250) ,
	@TEN NVARCHAR (250) ,
	@GIOITINH NVARCHAR (3) ,
	@NGAYSINH DATE ,
	@DANTOC NVARCHAR (250) ,
	@DIACHI NVARCHAR (250) ,
	@QUEQUAN NVARCHAR (30) ,
	@SODIENTHOAI NVARCHAR(15) ,
	@EMAIL NVARCHAR (250) ,
	@KHOAHOC INT,
	@MANGANH CHAR(6)
)
AS
INSERT INTO SINHVIEN(MASV,HO,TEN,GIOITINH,NGAYSINH,DANTOC,DIACHI,QUEQUAN,SODIENTHOAI,EMAIL,KHOAHOC,MANGANH)
VALUES (@MASV,@HO,@TEN,@GIOITINH,@NGAYSINH,@DANTOC,@DIACHI,@QUEQUAN,@SODIENTHOAI,@EMAIL,@KHOAHOC,@MANGANH)
GO

CREATE PROC sp_editSinhVien(
	@MASV CHAR (12) ,
	@HO NVARCHAR (250) ,
	@TEN NVARCHAR (250) ,
	@GIOITINH NVARCHAR (3) ,
	@NGAYSINH DATE ,
	@DANTOC NVARCHAR (250) ,
	@DIACHI NVARCHAR (250) ,
	@QUEQUAN NVARCHAR (30) ,
	@SODIENTHOAI NVARCHAR(15) ,
	@EMAIL NVARCHAR (250) 
)
AS
UPDATE SINHVIEN
SET SINHVIEN.HO = @HO,SINHVIEN.TEN = @TEN,SINHVIEN.GIOITINH = @GIOITINH,SINHVIEN.NGAYSINH = @NGAYSINH,DANTOC = @DANTOC,SINHVIEN.DIACHI = @DIACHI,SINHVIEN.QUEQUAN = @QUEQUAN,SINHVIEN.SODIENTHOAI = @SODIENTHOAI,SINHVIEN.EMAIL = @EMAIL
WHERE  MASV = @MASV
GO


CREATE PROC sp_getLastIDSinhVien
AS
SELECT TOP 1 * FROM SINHVIEN
ORDER BY SINHVIEN.id DESC
GO

CREATE PROC sp_addNganh(
	@MANGANH CHAR (6) ,
	@TENNGANH NVARCHAR (250) 
)
AS
INSERT INTO NGANH(MANGANH,TENNGANH)
VALUES (@MANGANH,@TENNGANH)
GO

CREATE PROC get_AllNganh
AS
SELECT * FROM NGANH
GO


exec sp_addNganh 'DT',N'CÔNG NGHỆ KĨ THUẬT ĐIỆN TỬ VÀ TRUYỀN THÔNG'
exec sp_addNganh 'TT',N'CÔNG NGHỆ THÔNG TIN'
exec sp_addNganh 'QT',N'QUẢN TRỊ KINH DOANH'
exec sp_addNganh 'DH',N'THIẾT KẾ ĐỒ HỌA'
exec sp_addNganh 'MT',N'TRUYỀN THÔNG VÀ MẠNG MÁY TÍNH'

exec sp_addSinhVien '23211TT0001',N'Nguyễn',N'Quốc Bảo','Nam','1/1/2003','Kinh',N'Quận 3 Thành Phố Hồ Chí Minh',N'Bình Định','0123456789','nguyenquocbao@gmail.com','23','QT';
exec sp_addSinhVien '23211TT0002',N'Trần',N'Thị Xuân',N'Nữ','3/5/2004','Kinh',N'Quận 1 Thành Phố Hồ Chí Minh',N'Long An','01234513242','tranthixuan@gmail.com','23','TT';
exec sp_addSinhVien '23211TT0003',N'Đỗ',N'Quốc Hùng','Nam','12/1/2004','Kinh',N'Quận 4 Thành Phố Hồ Chí Minh',N'Cà Mau','032312313242','tranthixuan@gmail.com','23','DT';

exec sp_createUser 'thinhle','123',1;

exec sp_createUser 'quang98','123',2;



select * from USERS;
exec sp_login 'thinhle','123'

CREATE PROC sp_getallsinhvien
AS
select SINHVIEN.*,NGANH.TENNGANH from SINHVIEN
inner join NGANH ON SINHVIEN.MANGANH = NGANH.MANGANH
ORDER BY SINHVIEN.id DESC
GO

CREATE PROC sp_searchsinhvien(
	@TEN NVARCHAR (250) 
)
AS
select SINHVIEN.*,NGANH.TENNGANH from SINHVIEN
inner join NGANH ON SINHVIEN.MANGANH = NGANH.MANGANH
WHERE SINHVIEN.TEN LIKE '%' + @TEN + '%' OR SINHVIEN.HO LIKE '%' + @TEN + '%' OR SINHVIEN.MASV LIKE '%' + @TEN + '%' OR CONCAT(SINHVIEN.HO,' ',SINHVIEN.TEN) LIKE '%' + @TEN + '%';
GO

CREATE PROC sp_deletesinhvien(
	@MASV CHAR (12) 
)
AS
DELETE FROM SINHVIEN WHERE MASV =@MASV
GO
select * from sinhvien

/*Reset id tự động tăng*/
CREATE PROC sp_resetID(
	@ID int
)
AS
DBCC CHECKIDENT("SINHVIEN", RESEED, @ID)
GO

/*drop ; */

/* DROP table sinhvien  */
/* Mon Hoc*/
CREATE TABLE MONHOC
(
MAMH CHAR(12) NOT NULL,
TENMH NVARCHAR(250) NOT NULL,
NIENKHOA INT NOT NULL,
HOCKY INT NOT NULL,
SOTIEN INT NOT NULL,
MAKHOA CHAR(6) NOT NULL,
MANGANH CHAR(6) NULL,
PRIMARY KEY(MAMH)

);
GO

CREATE PROC sp_getallMonHoc
AS
SELECT * FROM MONHOC
GO

CREATE PROC sp_getAllMonHocByNganh(
	@MANGANH CHAR(6)
)
AS 
SELECT * FROM MONHOC
WHERE MONHOC.MANGANH = @MANGANH
GO

CREATE PROC sp_searchMonHoc
(
@TENMH NVARCHAR(250)
)
AS
SELECT * FROM MONHOC WHERE MONHOC.TENMH LIKE '%' + @TENMH + '%';
GO

GO
CREATE PROC sp_deleteMonHoc
(
@MAMH CHAR(12)
)
AS
DELETE FROM MONHOC
WHERE MAMH = @MAMH
GO
SELECT * FROM MONHOC
GO

CREATE PROC sp_addMonHoc
(
@MAMH CHAR(12),
@TENMH NVARCHAR(250),
@NIENKHOA INT,
@HOCKY INT,
@SOTIEN INT,
@MAKHOA CHAR(6),
@MANGANH CHAR(6)
)
AS
INSERT INTO MONHOC(MAMH,TENMH,NIENKHOA,HOCKY,SOTIEN,MAKHOA,MANGANH)
VALUES (@MAMH,@TENMH,@NIENKHOA,@HOCKY,@SOTIEN,@MAKHOA,@MANGANH)
GO

exec sp_addMonHoc 'MH001',N'Lập trình ứng dụng 1','2023','1','10000','CNTT','TT';
exec sp_addMonHoc 'MH002',N'Kiểm thử phần mềm','2023','1','10000','CNTT','TT';
exec sp_addMonHoc 'MH003',N'Lập trình java','2023','1','10000','CNTT','TT';

exec sp_addMonHoc 'MH004',N'Xử lý ảnh','2023','1','10000','CNTT','DH';
exec sp_addMonHoc 'MH005',N'Xử lý phim','2023','1','10000','CNTT','DH';
exec sp_addMonHoc 'MH006',N'Nhiếp ảnh','2023','1','10000','CNTT','DH';

exec sp_addMonHoc 'MH007',N'Kinh tế vĩ mô','2023','1','10000','CNTT','QT';
exec sp_addMonHoc 'MH008',N'Nghiên cứu thị trường','2023','1','10000','CNTT','QT';
exec sp_addMonHoc 'MH009',N'Quản lý chuỗi cung ứng','2023','1','10000','CNTT','QT';

exec sp_addMonHoc 'MH0010',N'Quản trị linux','2023','1','10000','CNTT','MT';
exec sp_addMonHoc 'MH0011',N'Bảo mật mạng','2023','1','10000','CNTT','MT';
exec sp_addMonHoc 'MH0012',N'Lập trình Python','2023','1','10000','CNTT','MT';

exec sp_addMonHoc 'MH0013',N'Kỹ thuật số','2023','1','10000','CNTT','DT';
exec sp_addMonHoc 'MH0014',N'Vi  điều  khiển','2023','1','10000','CNTT','DT';
exec sp_addMonHoc 'MH0015',N'Thông  tin  vệ tinh','2023','1','10000','CNTT','DT';

exec sp_addLopHocPhan 'MH001','LH001',N'Nguyễn Văn Huy',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH002','LH002',N'Nguyễn Văn Huy',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH003','LH003',N'Nguyễn Văn Huy',N'B202','12/22/2023','4/5/2024',60

exec sp_addLopHocPhan 'MH004','LH004',N'Trương Anh Tuấn',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH005','LH005',N'Trương Anh Tuấn',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH006','LH006',N'Trương Anh Tuấn',N'B202','12/22/2023','4/5/2024',60

exec sp_addLopHocPhan 'MH007','LH007',N'Hoàng Văn Phát',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH008','LH008',N'Hoàng Văn Phát',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH009','LH009',N'Hoàng Văn Phát',N'B202','12/22/2023','4/5/2024',60

exec sp_addLopHocPhan 'MH010','LH010',N'Phương Thị Mỹ Lan',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH011','LH011',N'Phương Thị Mỹ Lan',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH012','LH012',N'Phương Thị Mỹ Lan',N'B202','12/22/2023','4/5/2024',60

exec sp_addLopHocPhan 'MH013','LH013',N'Nguyễn Thị Hồng',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH014','LH014',N'Nguyễn Thị Hồng',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH015','LH015',N'Nguyễn Thị Hồng',N'B202','12/22/2023','4/5/2024',60

exec sp_addLopHocPhan 'MH016','LH016',N'Tạ Anh Khôi',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH017','LH017',N'Tạ Anh Khôi',N'B202','12/22/2023','4/5/2024',60
exec sp_addLopHocPhan 'MH018','LH018',N'Tạ Anh Khôi',N'B202','12/22/2023','4/5/2024',60


select * from SINHVIEN
select * from users
