CREATE DATABASE QuanLyDiemSinhVien;
GO

USE QuanLyDiemSinhVien;
GO

CREATE TABLE USERS (
	user_id int IDENTITY NOT NULL,
	username NVARCHAR (30) NOT NULL UNIQUE,
	password NVARCHAR(250) NOT NULL,
	isAdmin INT NOT NULL
);
GO

CREATE TABLE SINHVIEN(
	id int IDENTITY NOT NULL,
	MASV CHAR (12) NOT NULL,
	HO NVARCHAR (250) NOT NULL,
	TEN NVARCHAR (250) NOT NULL,
	GIOITINH NVARCHAR (3) NULL,
	NGAYSINH DATE ,
	DANTOC NVARCHAR (250) NULL,
	DIACHI NVARCHAR (250) NULL,
	QUEQUAN NVARCHAR (30) NULL,
	SODIENTHOAI NVARCHAR(15) NULL,
	EMAIL NVARCHAR (250) NULL,
	KHOAHOC INT NOT NULL,
	MANGANH CHAR(6)

	PRIMARY KEY(MASV)
);
GO

CREATE TABLE NGANH (
	MANGANH CHAR (6) NOT NULL,
	TENNGANH NVARCHAR (250) NOT NULL,
	PRIMARY KEY (MANGANH)
);
GO

CREATE TABLE USERS_SINHVIEN(
	user_id  int NOT NULL,
	MASV CHAR (6) NOT NULL,

);
GO

CREATE PROC sp_login(
	@username NVARCHAR (30)  ,
	@password NVARCHAR(250) 
)
AS
SELECT * FROM USERS WHERE USERS.username = @username AND USERS.password = @password;
GO

CREATE PROC sp_createUser(
	@username NVARCHAR (30),
	@password NVARCHAR(250),
	@isAdmin INT 
)
AS
INSERT INTO USERS(username,password,isAdmin)
VALUES (@username,@password,@isAdmin)
GO

CREATE PROC sp_addSinhVien(
	@MASV CHAR (12) ,
	@HO NVARCHAR (250) ,
	@TEN NVARCHAR (250) ,
	@GIOITINH NVARCHAR (3) ,
	@NGAYSINH DATE ,
	@DANTOC NVARCHAR (250) ,
	@DIACHI NVARCHAR (250) ,
	@QUEQUAN NVARCHAR (30) ,
	@SODIENTHOAI NVARCHAR(15) ,
	@EMAIL NVARCHAR (250) ,
	@KHOAHOC INT,
	@MANGANH CHAR(6)
)
AS
INSERT INTO SINHVIEN(MASV,HO,TEN,GIOITINH,NGAYSINH,DANTOC,DIACHI,QUEQUAN,SODIENTHOAI,EMAIL,KHOAHOC,MANGANH)
VALUES (@MASV,@HO,@TEN,@GIOITINH,@NGAYSINH,@DANTOC,@DIACHI,@QUEQUAN,@SODIENTHOAI,@EMAIL,@KHOAHOC,@MANGANH)
GO

CREATE PROC sp_editSinhVien(
	@MASV CHAR (12) ,
	@HO NVARCHAR (250) ,
	@TEN NVARCHAR (250) ,
	@GIOITINH NVARCHAR (3) ,
	@NGAYSINH DATE ,
	@DANTOC NVARCHAR (250) ,
	@DIACHI NVARCHAR (250) ,
	@QUEQUAN NVARCHAR (30) ,
	@SODIENTHOAI NVARCHAR(15) ,
	@EMAIL NVARCHAR (250) 
)
AS
UPDATE SINHVIEN
SET SINHVIEN.HO = @HO,SINHVIEN.TEN = @TEN,SINHVIEN.GIOITINH = @GIOITINH,SINHVIEN.NGAYSINH = @NGAYSINH,DANTOC = @DANTOC,SINHVIEN.DIACHI = @DIACHI,SINHVIEN.QUEQUAN = @QUEQUAN,SINHVIEN.SODIENTHOAI = @SODIENTHOAI,SINHVIEN.EMAIL = @EMAIL
WHERE  MASV = @MASV
GO


CREATE PROC sp_getLastIDSinhVien
AS
SELECT TOP 1 * FROM SINHVIEN
ORDER BY SINHVIEN.id DESC
GO

CREATE PROC sp_addNganh(
	@MANGANH CHAR (6) ,
	@TENNGANH NVARCHAR (250) 
)
AS
INSERT INTO NGANH(MANGANH,TENNGANH)
VALUES (@MANGANH,@TENNGANH)
GO

CREATE PROC get_AllNganh
AS
SELECT * FROM NGANH
GO


exec sp_addNganh 'DT',N'CÔNG NGHỆ KĨ THUẬT ĐIỆN TỬ VÀ TRUYỀN THÔNG'
exec sp_addNganh 'TT',N'CÔNG NGHỆ THÔNG TIN'
exec sp_addNganh 'QT',N'QUẢN TRỊ KINH DOANH'
exec sp_addNganh 'DH',N'THIẾT KẾ ĐỒ HỌA'
exec sp_addNganh 'MT',N'TRUYỀN THÔNG VÀ MẠNG MÁY TÍNH'

exec sp_addSinhVien '23211TT0001',N'Nguyễn',N'Quốc Bảo','Nam','1/1/2003','Kinh',N'Quận 3 Thành Phố Hồ Chí Minh',N'Bình Định','0123456789','nguyenquocbao@gmail.com','23','QT';
exec sp_addSinhVien '23211TT0002',N'Trần',N'Thị Xuân',N'Nữ','3/5/2004','Kinh',N'Quận 1 Thành Phố Hồ Chí Minh',N'Long An','01234513242','tranthixuan@gmail.com','23','TT';
exec sp_addSinhVien '23211TT0003',N'Đỗ',N'Quốc Hùng','Nam','12/1/2004','Kinh',N'Quận 4 Thành Phố Hồ Chí Minh',N'Cà Mau','032312313242','tranthixuan@gmail.com','23','DT';

exec sp_createUser 'thinhle','123',1;

exec sp_createUser 'quang98','123',2;



select * from USERS;
exec sp_login 'thinhle','123'

CREATE PROC sp_getallsinhvien
AS
select SINHVIEN.*,NGANH.TENNGANH from SINHVIEN
inner join NGANH ON SINHVIEN.MANGANH = NGANH.MANGANH
ORDER BY SINHVIEN.id DESC
GO

CREATE PROC sp_searchsinhvien(
	@TEN NVARCHAR (250) 
)
AS
select SINHVIEN.*,NGANH.TENNGANH from SINHVIEN
inner join NGANH ON SINHVIEN.MANGANH = NGANH.MANGANH
WHERE SINHVIEN.TEN LIKE '%' + @TEN + '%' OR SINHVIEN.HO LIKE '%' + @TEN + '%' OR SINHVIEN.MASV LIKE '%' + @TEN + '%' OR CONCAT(SINHVIEN.HO,' ',SINHVIEN.TEN) LIKE '%' + @TEN + '%';
GO

CREATE PROC sp_deletesinhvien(
	@MASV CHAR (12) 
)
AS
DELETE FROM SINHVIEN WHERE MASV =@MASV
GO
select * from sinhvien


/*drop ; */

/* DROP table sinhvien  */
exec sp_deletesinhvien '2311cboChuye'

CREATE TABLE MONHOC
(
MAMH CHAR(12) NOT NULL,
TENMH NVARCHAR(250) NOT NULL,
NIENKHOA INT NOT NULL,
HOCKY INT NOT NULL,
SOTIEN INT NOT NULL,
MAKHOA CHAR NOT NULL,

);
GO

CREATE PROC sp_getallMonHoc
AS
SELECT * FROM MONHOC
GO

CREATE PROC sp_searchMonHoc
(
@TENMH NVARCHAR(250)
)
AS
SELECT * FROM MONHOC WHERE MONHOC.TENMH LIKE '%' + @TENMH + '%';
GO

GO
CREATE PROC sp_deleteMonHoc
(
@MAMH CHAR(12)
)
AS
DELETE FROM MONHOC
WHERE MAMH = @MAMH
GO
SELECT * FROM MONHOC
GO

CREATE PROC sp_addMonHoc
(
@MAMH CHAR(12),
@TENMH NVARCHAR(250),
@NIENKHOA INT,
@HOCKY INT,
@SOTIEN INT,
@MAKHOA CHAR(6)
)
AS
INSERT INTO MONHOC(MAMH,TENMH,NIENKHOA,HOCKY,SOTIEN,MAKHOA)
VALUES (@MAMH,@TENMH,@NIENKHOA,@HOCKY,@SOTIEN,@MAKHOA)
GO

DROP PROC sp_addMonHoc
exec sp_addMonHoc 'MH001',N'Lập trình ứng dụng 1','2023','1','10000','T';
exec sp_addMonHoc 'MH002',N'Kiểm thử phần mềm','2023','1','10000','T';
exec sp_addMonHoc 'MH003',N'Lập trình java','2023','1','10000','T';